name: af3-console
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - nodefaults
dependencies:
  - python=3.12
  - pyside6>=6.6,<7
  - numpy>=1.26,<3
  - pandas>=2.2,<4
  - matplotlib>=3.8,<4
  - six>=1.16,<2
  - python-dateutil>=2.9,<3
  - zstandard>=0.23,<1
  - qtawesome>=1.3,<2
